#!/bin/fish

set BASENAME (echo $argv[1] | sed 's/.tex$//g')
set CLEANDIR (echo '.'$BASENAME'_extra')

mkdir -p $CLEANDIR

echo "pdflatex -shell-escape -output-directory=$CLEANDIR $argv[1]"

mv $CLEANDIR/$BASENAME.pdf .
